[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = [
  'cp backend-package.json package.json',
  'yarn install --frozen-lockfile'
]

[phases.build]
cmds = ['yarn build']

[start]
cmd = 'yarn start'
