[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['yarn install --frozen-lockfile']

[phases.build]
cmds = [
  'yarn build:prod',
  'ls -la dist/',
  'ls -la dist/backend/',
  'ls -la dist/backend/devswhorun-api/'
]

[start]
cmd = 'node dist/backend/devswhorun-api/main.js'
